# Generated by Django 4.1.3 on 2023-01-10 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram_bot', '0004_user_has_used_promocode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromocodesGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('count', models.PositiveIntegerField()),
                ('expire_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=8, unique=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telegram_bot.user')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promocodes.promocodesgroup')),
            ],
        ),
    ]
