# Generated by Django 4.1.3 on 2023-01-14 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0006_merge_20230114_0804'),
        ('promocodes', '0002_alter_promocodesgroup_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocodesgroup',
            name='count',
        ),
        migrations.AlterField(
            model_name='promocode',
            name='activated_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telegram_bot.user'),
        ),
    ]
