# Generated by Django 4.1.3 on 2022-12-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationalerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='Was payment used for subscription renewal'),
        ),
    ]
