# Generated by Django 4.1.3 on 2023-01-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0003_alter_user_subscribed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_used_promocode',
            field=models.BooleanField(default=False),
        ),
    ]
