# Generated by Django 4.1.3 on 2023-01-14 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0005_rename_has_used_promocode_user_has_activated_promocode'),
        ('telegram_bot', '0005_scheduledtask'),
    ]

    operations = [
    ]
