# Generated by Django 4.1.3 on 2022-11-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('max_users_count', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
