# Generated by Django 4.1.3 on 2023-01-11 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='max_users_count',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='server',
            name='url',
            field=models.URLField(max_length=32, unique=True),
        ),
    ]
