# Generated by Django 4.1.3 on 2023-01-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard', '0002_server_name_alter_server_max_users_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(blank=True, help_text='Optional', max_length=64, null=True, unique=True),
        ),
    ]
